[tool.poetry]
name = "git-sync"
version = "0.1.2"
description = "Synchronize local git repo with remotes"
authors = ["Alice Purcell <Alice.Purcell.39@gmail.com>"]

[tool.poetry.scripts]
git-sync = "git_sync:main"

[tool.poetry.dependencies]
python = "^3.8"
aiographql-client = "^1.0.3"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.2"
flake8 = "^4.0.1"
mypy = "^0.950"

[tool.isort]
profile = "black"

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
